In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
pd.set_option("display.max_columns", None)
data = pd.read_csv("Data/preprocessed_data.csv", delimiter=",")
data.head(20)

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,Admission grade,Displaced,Educational special needs,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,International,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target,Admission grade bins,Age group,Unemployment rate bins
0,1,17,5,171,1,1,122.0,1.0,19,12,5,9,127.3,1,0,0,1,1.0,0,20.0,0,0,0,0,0,0.000000,0,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout,NaN,18-22,10-15%
1,1,15,1,9254,1,1,160.0,1.0,1,3,3,3,142.5,1,0,0,0,1.0,0,19.0,0,0,6,6,6,14.000000,0,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate,NaN,18-22,10-15%
2,1,1,5,9070,1,1,122.0,1.0,37,37,9,9,124.8,1,0,0,0,1.0,0,19.0,0,0,6,0,0,0.000000,0,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout,NaN,18-22,10-15%
3,1,17,2,9773,1,1,122.0,1.0,38,37,5,3,119.6,1,0,0,1,0.0,0,20.0,0,0,6,8,6,13.428571,0,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate,NaN,18-22,5-10%
4,2,39,1,8014,0,1,100.0,1.0,37,38,9,9,141.5,0,0,0,1,0.0,0,34.0,0,0,6,9,5,12.333333,0,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate,NaN,28-35,10-15%
5,2,39,1,9991,0,19,133.1,1.0,37,37,9,7,114.8,0,0,1,1,1.0,0,34.0,0,0,5,10,5,11.857143,0,0,5,17,5,11.500000,5,16.2,0.3,-0.92,Graduate,NaN,28-35,15%+
6,1,1,1,9500,1,1,142.0,1.0,19,38,7,10,128.4,1,0,0,1,0.0,1,18.0,0,0,7,9,7,13.300000,0,0,8,8,8,14.345000,0,15.5,2.8,-4.06,Graduate,NaN,18-22,15%+
7,1,18,4,9254,1,1,119.0,1.0,37,37,9,9,113.1,1,0,0,0,1.0,0,22.0,0,0,5,5,0,0.000000,0,0,5,5,0,0.000000,0,15.5,2.8,-4.06,Dropout,NaN,18-22,15%+
8,1,1,3,9238,1,1,137.0,62.0,1,1,9,9,129.3,0,0,0,1,0.0,1,21.0,1,0,6,8,6,13.875000,0,0,6,7,6,14.142857,0,16.2,0.3,-0.92,Graduate,NaN,18-22,15%+
9,1,1,1,9238,1,1,138.0,1.0,1,19,4,7,123.0,1,0,1,0,0.0,0,18.0,0,0,6,9,5,11.400000,0,0,6,14,2,13.500000,0,8.9,1.4,3.51,Dropout,NaN,18-22,5-10%
10,1,1,1,9670,1,1,139.0,1.0,38,19,5,7,130.6,1,0,0,1,0.0,0,18.0,0,0,6,6,6,12.333333,0,0,6,7,5,14.200000,0,13.9,-0.3,0.79,Graduate,NaN,18-22,10-15%
11,1,1,1,9500,1,1,136.0,1.0,19,38,9,9,119.3,1,0,0,1,0.0,1,18.0,0,0,8,8,7,13.214286,0,0,8,8,7,13.214286,0,12.7,3.7,-1.70,Graduate,NaN,18-22,10-15%
12,1,1,2,9853,1,1,133.0,1.0,19,37,4,9,130.2,1,0,0,1,0.0,0,19.0,0,0,6,6,0,0.000000,0,0,6,0,0,0.000000,0,12.7,3.7,-1.70,Dropout,NaN,18-22,10-15%
13,1,53,1,9254,1,42,110.0,1.0,1,1,4,7,111.8,1,0,0,1,0.0,1,21.0,0,0,6,7,6,10.571429,0,0,6,8,5,11.000000,0,8.9,1.4,3.51,Graduate,NaN,18-22,5-10%
14,1,1,1,9085,1,1,149.0,1.0,38,37,5,5,137.1,1,0,0,1,0.0,1,18.0,0,0,5,7,4,13.250000,0,0,5,5,5,12.000000,0,10.8,1.4,1.74,Graduate,NaN,18-22,10-15%
15,1,1,1,9773,1,1,127.0,1.0,19,37,9,3,120.7,1,0,0,1,0.0,0,20.0,0,0,6,6,5,13.200000,0,0,6,7,0,0.000000,0,15.5,2.8,-4.06,Dropout,NaN,18-22,15%+
16,1,17,2,9500,1,1,135.0,1.0,19,1,5,4,127.3,1,0,0,1,0.0,0,18.0,0,0,7,8,7,13.306250,0,0,8,8,8,14.545000,0,15.5,2.8,-4.06,Graduate,NaN,18-22,15%+
17,1,1,1,9130,1,1,137.0,1.0,3,19,3,5,136.3,1,0,0,1,0.0,0,20.0,0,0,5,8,4,12.500000,1,0,5,8,4,12.250000,2,10.8,1.4,1.74,Graduate,NaN,18-22,10-15%
18,1,1,1,9853,1,1,140.0,1.0,19,19,7,7,124.6,1,0,0,1,0.0,0,18.0,0,0,7,7,6,11.666667,0,0,7,8,6,13.500000,0,16.2,0.3,-0.92,Enrolled,NaN,18-22,15%+
19,1,1,3,171,1,1,122.0,1.0,1,1,9,8,120.3,0,0,0,1,0.0,1,21.0,0,0,0,0,0,0.000000,0,0,0,0,0,0.000000,0,11.1,0.6,2.02,Graduate,NaN,18-22,10-15%

In [8]:
# Preprocessing

# Encoding only categorical columns
categorical_columns = [
    'Marital status', 'Application mode', 'Application order', 'Course',
    'Daytime/evening attendance', 'Previous qualification', 'Nacionality',
    "Mother's qualification", "Father's qualification", "Mother's occupation",
    "Father's occupation", 'Displaced', 'Educational special needs', 'Debtor',
    'Tuition fees up to date', 'Gender', 'Scholarship holder', 'International', 'Target',
    'Age group', 'Unemployment rate bins'
]

for col in categorical_columns:
    data[col] = data[col].astype(str)

# One hot encoding
encoded_data = pd.get_dummies(data)

# Dropping all non categorical columns
encoded_data = encoded_data.drop(columns=["Previous qualification (grade)", "Admission grade",
                           "Age at enrollment", "Curricular units 1st sem (credited)",
                           "Curricular units 1st sem (enrolled)", "Curricular units 1st sem (evaluations)",
                           "Curricular units 1st sem (approved)", "Curricular units 1st sem (grade)",
                           "Curricular units 1st sem (without evaluations)", "Curricular units 2nd sem (credited)",
                           "Curricular units 2nd sem (enrolled)", "Curricular units 2nd sem (evaluations)",
                           "Curricular units 2nd sem (approved)", "Curricular units 2nd sem (grade)",
                           "Curricular units 2nd sem (without evaluations)", "Unemployment rate",
                           "Inflation rate", "GDP"])

encoded_data.head(20)

,Marital status_1,Marital status_2,Marital status_3,Marital status_4,Marital status_5,Marital status_6,Application mode_1,Application mode_10,Application mode_15,Application mode_16,Application mode_17,Application mode_18,Application mode_2,Application mode_26,Application mode_27,Application mode_39,Application mode_42,Application mode_43,Application mode_44,Application mode_5,Application mode_51,Application mode_53,Application mode_57,Application mode_7,Application order_0,Application order_1,Application order_2,Application order_3,Application order_4,Application order_5,Application order_6,Application order_9,Course_171,Course_33,Course_8014,Course_9003,Course_9070,Course_9085,Course_9119,Course_9130,Course_9147,Course_9238,Course_9254,Course_9500,Course_9556,Course_9670,Course_9773,Course_9853,Course_9991,Daytime/evening attendance_0,Daytime/evening attendance_1,Previous qualification_1,Previous qualification_10,Previous qualification_12,Previous qualification_14,Previous qualification_15,Previous qualification_19,Previous qualification_2,Previous qualification_3,Previous qualification_38,Previous qualification_39,Previous qualification_4,Previous qualification_40,Previous qualification_42,Previous qualification_43,Previous qualification_5,Previous qualification_6,Previous qualification_9,Nacionality_1.0,Nacionality_100.0,Nacionality_101.0,Nacionality_103.0,Nacionality_105.0,Nacionality_108.0,Nacionality_109.0,Nacionality_11.0,Nacionality_13.0,Nacionality_14.0,Nacionality_17.0,Nacionality_2.0,Nacionality_21.0,Nacionality_22.0,Nacionality_24.0,Nacionality_25.0,Nacionality_26.0,Nacionality_32.0,Nacionality_41.0,Nacionality_6.0,Nacionality_62.0,Nacionality_nan,Mother's qualification_1,Mother's qualification_10,Mother's qualification_11,Mother's qualification_12,Mother's qualification_14,Mother's qualification_18,Mother's qualification_19,Mother's qualification_2,Mother's qualification_22,Mother's qualification_26,Mother's qualification_27,Mother's qualification_29,Mother's qualification_3,Mother's qualification_30,Mother's qualification_34,Mother's qualification_35,Mother's qualification_36,Mother's qualification_37,Mother's qualification_38,Mother's qualification_39,Mother's qualification_4,Mother's qualification_40,Mother's qualification_41,Mother's qualification_42,Mother's qualification_43,Mother's qualification_44,Mother's qualification_5,Mother's qualification_6,Mother's qualification_9,Father's qualification_1,Father's qualification_10,Father's qualification_11,Father's qualification_12,Father's qualification_13,Father's qualification_14,Father's qualification_18,Father's qualification_19,Father's qualification_2,Father's qualification_20,Father's qualification_22,Father's qualification_25,Father's qualification_26,Father's qualification_27,Father's qualification_29,Father's qualification_3,Father's qualification_30,Father's qualification_31,Father's qualification_33,Father's qualification_34,Father's qualification_35,Father's qualification_36,Father's qualification_37,Father's qualification_38,Father's qualification_39,Father's qualification_4,Father's qualification_40,Father's qualification_41,Father's qualification_42,Father's qualification_43,Father's qualification_44,Father's qualification_5,Father's qualification_6,Father's qualification_9,Mother's occupation_0,Mother's occupation_1,Mother's occupation_10,Mother's occupation_122,Mother's occupation_123,Mother's occupation_125,Mother's occupation_131,Mother's occupation_132,Mother's occupation_134,Mother's occupation_141,Mother's occupation_143,Mother's occupation_144,Mother's occupation_151,Mother's occupation_152,Mother's occupation_153,Mother's occupation_171,Mother's occupation_173,Mother's occupation_175,Mother's occupation_191,Mother's occupation_192,Mother's occupation_193,Mother's occupation_194,Mother's occupation_2,Mother's occupation_3,Mother's occupation_4,Mother's occupation_5,Mother's occupation_6,Mother's occupation_7,Mother's occupation_8,Mother's occupation_9,Mother's occupation_90,Mother's occupation_99,Father's occupation_0,Father's occupation_1,Father's occupation_10,Father's occupation_101,Father's occupation_102,Father's occupation_103,Father's occupation_112,Father's occupation_114,Father's occupation_121,Father's occupation_122,Father's occupation_123,Father's occupation_124,Father's occupation_131,Father's occupation_132,Father's occupation_134,Father's occupation_135,Father's occupation_141,Father's occupation_143,Father's occupation_144,Father's occupation_151,Father's occupation_152,Father's occupation_153,Father's occupation_154,Father's occupation_161,Father's occupation_163,Father's occupation_171,Father's occupation_172,Father's occupation_174,Father's occupation_175,Father's occupation_181,Father's occupation_182,Father's occupation_183,Father's occupation_192,Father's occupation_193,Father's occupation_194,Father's occupation_195,Father's occupation_2,Father's occupation_3,Father's occupation_4,Father's occupation_5,Father's occupation_6,Father's occupation_7,Father's occupation_8,Father's occupation_9,Father's occupation_90,Father's occupation_99,Displaced_0,Displaced_1,Educational special needs_0,Educational special needs_1,Debtor_0,Debtor_1,Tuition fees up to date_0,Tuition fees up to date_1,Gender_0.0,Gender_1.0,Gender_2.0,Scholarship holder_0,Scholarship holder_1,International_0,International_1,Target_Dropout,Target_Enrolled,Target_Graduate,Admission grade bins_91-100,Age group_18-22,Age group_23-27,Age group_28-35,Unemployment rate bins_10-15%,Unemployment rate bins_15%+,Unemployment rate bins_5-10%
0,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,True,False,False,True,False,True,False,True,False,True,False,True,False,False,False,True,False,False,True,False,False
1,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,True,False,True,False,False,True,False,True,False,True,False,False,False,True,False,True,False,False,True,False,False
2,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,True,False,True,False,False,True,False,True,False,True,False,True,False,False,False,True,False,False,True,False,False
3,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,True,True,False,False,True,False,True,False,False,False,True,False,True,False,False,False,False,True
4,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,True,False,False,True,True,False,False,True,False,True,False,False,False,True,False,False,False,True,True,False,False
5,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,True,False,True,False,True,False,True,False,True,False,False,False,True,False,False,False,True,False,True,False
6,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,True,True,False,False,False,True,True,False,False,False,True,False,True,False,False,False,True,False
7,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,True,False,True,False,False,True,False,True,False,True,False,True,False,False,False,True,False,False,False,True,False
8,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,True,False,False,True,True,False,False,False,True,False,True,False,False,True,False,True,False,False,False,True,False

In [59]:
# Mining Frequent Itemsets

def apriori_itemsets(data, support, maxlen=10):
    # use sets
    candidates = []
    frequent = []
    all_frequent = []
    min_support_count = support*data.shape[0]
    k = 1
    
    # Step 0
    # loop through columns and generate candidate k = 1 itemsets
    for column in data:
        itemset = {column}
        itemset = frozenset(itemset)
        candidates.append(itemset)
    # Check if each is frequent, if it is add it to frequent
    for candidate in candidates:
        support_count = 0
        # can't index sets so get the item out of the candidate set like this
        for item in candidate:
            break
        for transaction in data.loc[:,item]:
            if transaction:
                support_count += 1
        if support_count >= min_support_count:
            frequent.append(candidate)
    all_frequent = all_frequent + frequent

    # Main loop
    # repeat until frequent is empty or k=max
    while frequent != [] and k < maxlen:
        candidates = []
        
        # Loop through frequent and generate candidate k+1 itemsets by combining k itemsets
        for i in range(len(frequent) - 1):
            for j in range(i+1, len(frequent)):
                new_itemset = frequent[i].union(frequent[j])
                candidates.append(new_itemset)
        candidates = set(candidates)
        
        # Remove old frequents
        frequent = []
        
        # Check if each is frequent and add it to frequent
        for candidate in candidates:
            support_count = 0
            for index, row in data.iterrows():
                present = True
                for item in candidate:
                    if not row[item]:
                        present = False
                        break
                if present:
                    support_count += 1
            if support_count >= min_support_count:
                frequent.append(candidate)
        all_frequent = all_frequent + frequent
        k += 1
    return all_frequent

In [61]:
# Call function
frequent_itemsets = apriori_itemsets(encoded_data, support=0.05, maxlen=2)
print(frequent_itemsets)

KeyboardInterrupt:

In [88]:
# Mining Frequent Rules

import itertools

def AprioriRules(data, frequent_itemsets, min_confidence):
    # association rules are data frames
    # rules are added by first constructing a list of the three components
    # then concatenating the rules df and the list
    rules = pd.DataFrame(columns=["antecedent", "consequent", "confidence"])

    # loop through itemsets and generate all non-empty subsets
    for itemset in frequent_itemsets:
        subsets = []
        for length in range(1, len(itemset)):
            # generates all combinations of the subset of a certain length
            subsets.extend(itertools.combinations(itemset, length))
        sub_frozensets = [frozenset(subset) for subset in subsets]
        
        # generate all rules using, "s -> (I - s)" checking if, support of I / support of s > min confidence
        # Where I is a frequent itemset, and s is a subset of that itemset
    
        # Steps
        for subset in sub_frozensets:
            # Define antecedent as the subset
            antecedent = subset
            # Define consequent as the itemset - the subset
            consequent = itemset.difference(subset)
            # Check confidence and if above threshold then add to rules
            # confidence = support of I / support of s
            itemset_support_count = 0
            for index, row in data.iterrows():
                present = True
                for item in itemset:
                    if not row[item]:
                        present = False
                        break
                if present:
                    itemset_support_count += 1

            subset_support_count = 0
            for index, row in data.iterrows():
                present = True
                for item in subset:
                    if not row[item]:
                        present = False
                        break
                if present:
                    subset_support_count += 1
                    
            confidence = itemset_support_count / subset_support_count
            if confidence >= min_confidence:
                rules = pd.concat([rules, pd.DataFrame([[antecedent, consequent, confidence]], columns=["antecedent", "consequent", "confidence"])], ignore_index=True)
            print(rules, "\n\n\n")
    return rules

In [89]:
rules = AprioriRules(encoded_data, frequent_itemsets, min_confidence=0.7)
rules.head(10)

Empty DataFrame
Columns: [antecedent, consequent, confidence]
Index: []



                   antecedent          consequent  confidence
0  (Father's qualification_1)  (Marital status_1)    0.954708

/var/folders/vl/9w9rx2q5545bh7r3xxpffqh40000gn/T/ipykernel_44327/1595090191.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  rules = pd.concat([rules, pd.DataFrame([[antecedent, consequent, confidence]], columns=["antecedent", "consequent", "confidence"])], ignore_index=True)

                   antecedent          consequent  confidence
0  (Father's qualification_1)  (Marital status_1)    0.954708



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654
4               (Age group_28-35)       (Displaced_0)    0.798278



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654
4               (Age group_28-35)       (Displaced_0)    0.798278



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654
4               (Age group_28-35)       (Displaced_0)    0.798278



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654
4               (Age group_28-35)       (Displaced_0)    0.798278
5     (Mother's qualification_37)  (Marital status_1)    0.708861



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654
4               (Age group_28-35)       (Displaced_0)    0.798278
5     (Mother's qualification_37)  (Marital status_1)    0.708861



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654
4               (Age group_28-35)       (Displaced_0)    0.798278
5     (Mother's qualification_37)  (Marital status_1)    0.708861



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654
4               (Age group_28-35)       (Displaced_0)    0.798278
5     (Mother's qualification_37)  (Marital status_1)    0.708861



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654
4               (Age group_28-35)       (Displaced_0)    0.798278
5     (Mother's qualification_37)  (Marital status_1)    0.708861
6         (Father's occupation_9)   (International_0)    0.964472



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654
4               (Age group_28-35)       (Displaced_0)    0.798278
5     (Mother's qualification_37)  (Marital status_1)    0.708861
6         (Father's occupation_9)   (International_0)    0.964472



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654
4               (Age group_28-35)       (Displaced_0)    0.798278
5     (Mother's qualification_37)  (Marital status_1)    0.708861
6         (Father's occupation_9)   (International_0)    0.964472



                       antecedent          consequent  confidence
0      (Father's qualification_1)  (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)   (International_0)    0.989107
2         (Mother's occupation_2)          (Debtor_0)    0.908784
3         (Mother's occupation_7)   (Nacionality_1.0)    0.976654
4               (Age group_28-35)       (Displaced_0)    0.798278
5     (Mother's qualification_37)  (Marital status_1)    0.708861
6         (Father's occupation_9)   (International_0)    0.964472



                       antecedent             consequent  confidence
0      (Father's qualification_1)     (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)      (International_0)    0.989107
2         (Mother's occupation_2)             (Debtor_0)    0.908784
3         (Mother's occupation_7)      (Nacionality_1.0)    0.976654
4               (Age group_28-35)          (Displaced_0)    0.798278
5     (Mother's qualification_37)     (Marital status_1)    0.708861
6         (Father's occupation_9)      (International_0)    0.964472
7                   (Course_9991)  (Application order_1)    0.956693



                       antecedent             consequent  confidence
0      (Father's qualification_1)     (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)      (International_0)    0.989107
2         (Mother's occupation_2)             (Debtor_0)    0.908784
3         (Mother's occupation_7)      (Nacionality_1.0)    0.976654
4               (Age group_28-35)          (Displaced_0)    0.798278
5     (Mother's qualification_37)     (Marital status_1)    0.708861
6         (Father's occupation_9)      (International_0)    0.964472
7                   (Course_9991)  (Application order_1)    0.956693



                       antecedent                     consequent  confidence
0      (Father's qualification_1)             (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)              (International_0)    0.989107
2         (Mother's occupation_2)                     (Debtor_0)    0.908784
3         (Mother's occupation_7)              (Nacionality_1.0)    0.976654
4               (Age group_28-35)                  (Displaced_0)    0.798278
5     (Mother's qualification_37)             (Marital status_1)    0.708861
6         (Father's occupation_9)              (International_0)    0.964472
7                   (Course_9991)          (Application order_1)    0.956693
8         (Father's occupation_5)  (Educational special needs_0)    0.985597



                       antecedent                     consequent  confidence
0      (Father's qualification_1)             (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)              (International_0)    0.989107
2         (Mother's occupation_2)                     (Debtor_0)    0.908784
3         (Mother's occupation_7)              (Nacionality_1.0)    0.976654
4               (Age group_28-35)                  (Displaced_0)    0.798278
5     (Mother's qualification_37)             (Marital status_1)    0.708861
6         (Father's occupation_9)              (International_0)    0.964472
7                   (Course_9991)          (Application order_1)    0.956693
8         (Father's occupation_5)  (Educational special needs_0)    0.985597
9                   (Course_9085)              (International_0)    0.964516



                       antecedent                     consequent  confidence
0      (Father's qualification_1)             (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)              (International_0)    0.989107
2         (Mother's occupation_2)                     (Debtor_0)    0.908784
3         (Mother's occupation_7)              (Nacionality_1.0)    0.976654
4               (Age group_28-35)                  (Displaced_0)    0.798278
5     (Mother's qualification_37)             (Marital status_1)    0.708861
6         (Father's occupation_9)              (International_0)    0.964472
7                   (Course_9991)          (Application order_1)    0.956693
8         (Father's occupation_5)  (Educational special needs_0)    0.985597
9                   (Course_9085)              (International_0)    0.964516



                        antecedent                     consequent  confidence
0       (Father's qualification_1)             (Marital status_1)    0.954708
1   (Daytime/evening attendance_0)              (International_0)    0.989107
2          (Mother's occupation_2)                     (Debtor_0)    0.908784
3          (Mother's occupation_7)              (Nacionality_1.0)    0.976654
4                (Age group_28-35)                  (Displaced_0)    0.798278
5      (Mother's qualification_37)             (Marital status_1)    0.708861
6          (Father's occupation_9)              (International_0)    0.964472
7                    (Course_9991)          (Application order_1)    0.956693
8          (Father's occupation_5)  (Educational special needs_0)    0.985597
9                    (Course_9085)              (International_0)    0.964516
10         (Father's occupation_4)  (Educational special needs_0)    0.983425



                        antecedent                     consequent  confidence
0       (Father's qualification_1)             (Marital status_1)    0.954708
1   (Daytime/evening attendance_0)              (International_0)    0.989107
2          (Mother's occupation_2)                     (Debtor_0)    0.908784
3          (Mother's occupation_7)              (Nacionality_1.0)    0.976654
4                (Age group_28-35)                  (Displaced_0)    0.798278
5      (Mother's qualification_37)             (Marital status_1)    0.708861
6          (Father's occupation_9)              (International_0)    0.964472
7                    (Course_9991)          (Application order_1)    0.956693
8          (Father's occupation_5)  (Educational special needs_0)    0.985597
9                    (Course_9085)              (International_0)    0.964516
10         (Father's occupation_4)  (Educational special needs_0)    0.983425



                        antecedent                     consequent  confidence
0       (Father's qualification_1)             (Marital status_1)    0.954708
1   (Daytime/evening attendance_0)              (International_0)    0.989107
2          (Mother's occupation_2)                     (Debtor_0)    0.908784
3          (Mother's occupation_7)              (Nacionality_1.0)    0.976654
4                (Age group_28-35)                  (Displaced_0)    0.798278
5      (Mother's qualification_37)             (Marital status_1)    0.708861
6          (Father's occupation_9)              (International_0)    0.964472
7                    (Course_9991)          (Application order_1)    0.956693
8          (Father's occupation_5)  (Educational special needs_0)    0.985597
9                    (Course_9085)              (International_0)    0.964516
10         (Father's occupation_4)  (Educational special needs_0)    0.983425
11           (Application mode_39)              (Nacionality_1.0)    0.962366



                        antecedent                     consequent  confidence
0       (Father's qualification_1)             (Marital status_1)    0.954708
1   (Daytime/evening attendance_0)              (International_0)    0.989107
2          (Mother's occupation_2)                     (Debtor_0)    0.908784
3          (Mother's occupation_7)              (Nacionality_1.0)    0.976654
4                (Age group_28-35)                  (Displaced_0)    0.798278
5      (Mother's qualification_37)             (Marital status_1)    0.708861
6          (Father's occupation_9)              (International_0)    0.964472
7                    (Course_9991)          (Application order_1)    0.956693
8          (Father's occupation_5)  (Educational special needs_0)    0.985597
9                    (Course_9085)              (International_0)    0.964516
10         (Father's occupation_4)  (Educational special needs_0)    0.983425
11           (Application mode_39)              (Nacionality_1.0)    0.962366



                        antecedent                     consequent  confidence
0       (Father's qualification_1)             (Marital status_1)    0.954708
1   (Daytime/evening attendance_0)              (International_0)    0.989107
2          (Mother's occupation_2)                     (Debtor_0)    0.908784
3          (Mother's occupation_7)              (Nacionality_1.0)    0.976654
4                (Age group_28-35)                  (Displaced_0)    0.798278
5      (Mother's qualification_37)             (Marital status_1)    0.708861
6          (Father's occupation_9)              (International_0)    0.964472
7                    (Course_9991)          (Application order_1)    0.956693
8          (Father's occupation_5)  (Educational special needs_0)    0.985597
9                    (Course_9085)              (International_0)    0.964516
10         (Father's occupation_4)  (Educational special needs_0)    0.983425
11           (Application mode_39)              (Nacionality_1.0)    0.962366
12                   (Course_9085)                   (Gender_0.0)    0.809677



                        antecedent                     consequent  confidence
0       (Father's qualification_1)             (Marital status_1)    0.954708
1   (Daytime/evening attendance_0)              (International_0)    0.989107
2          (Mother's occupation_2)                     (Debtor_0)    0.908784
3          (Mother's occupation_7)              (Nacionality_1.0)    0.976654
4                (Age group_28-35)                  (Displaced_0)    0.798278
5      (Mother's qualification_37)             (Marital status_1)    0.708861
6          (Father's occupation_9)              (International_0)    0.964472
7                    (Course_9991)          (Application order_1)    0.956693
8          (Father's occupation_5)  (Educational special needs_0)    0.985597
9                    (Course_9085)              (International_0)    0.964516
10         (Father's occupation_4)  (Educational special needs_0)    0.983425
11           (Application mode_39)              (Nacionality_1.0)    0.962366
12                   (Course_9085)                   (Gender_0.0)    0.809677



                        antecedent                     consequent  confidence
0       (Father's qualification_1)             (Marital status_1)    0.954708
1   (Daytime/evening attendance_0)              (International_0)    0.989107
2          (Mother's occupation_2)                     (Debtor_0)    0.908784
3          (Mother's occupation_7)              (Nacionality_1.0)    0.976654
4                (Age group_28-35)                  (Displaced_0)    0.798278
5      (Mother's qualification_37)             (Marital status_1)    0.708861
6          (Father's occupation_9)              (International_0)    0.964472
7                    (Course_9991)          (Application order_1)    0.956693
8          (Father's occupation_5)  (Educational special needs_0)    0.985597
9                    (Course_9085)              (International_0)    0.964516
10         (Father's occupation_4)  (Educational special needs_0)    0.983425
11           (Application mode_39)              (Nacionality_1.0)    0.962366
12                   (Course_9085)                   (Gender_0.0)    0.809677
13                   (Course_9254)              (International_0)    0.966387



                        antecedent                     consequent  confidence
0       (Father's qualification_1)             (Marital status_1)    0.954708
1   (Daytime/evening attendance_0)              (International_0)    0.989107
2          (Mother's occupation_2)                     (Debtor_0)    0.908784
3          (Mother's occupation_7)              (Nacionality_1.0)    0.976654
4                (Age group_28-35)                  (Displaced_0)    0.798278
5      (Mother's qualification_37)             (Marital status_1)    0.708861
6          (Father's occupation_9)              (International_0)    0.964472
7                    (Course_9991)          (Application order_1)    0.956693
8          (Father's occupation_5)  (Educational special needs_0)    0.985597
9                    (Course_9085)              (International_0)    0.964516
10         (Father's occupation_4)  (Educational special needs_0)    0.983425
11           (Application mode_39)              (Nacionality_1.0)    0.962366
12                   (Course_9085)                   (Gender_0.0)    0.809677

                       antecedent                     consequent  confidence
0      (Father's qualification_1)             (Marital status_1)    0.954708
1  (Daytime/evening attendance_0)              (International_0)    0.989107
2         (Mother's occupation_2)                     (Debtor_0)    0.908784
3         (Mother's occupation_7)              (Nacionality_1.0)    0.976654
4               (Age group_28-35)                  (Displaced_0)    0.798278
5     (Mother's qualification_37)             (Marital status_1)    0.708861
6         (Father's occupation_9)              (International_0)    0.964472
7                   (Course_9991)          (Application order_1)    0.956693
8         (Father's occupation_5)  (Educational special needs_0)    0.985597
9                   (Course_9085)              (International_0)    0.964516